engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  fixme:
    enabled: true
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
      no-multiple-empty-lines:
        enabled: false  
ratings:
  paths:
  - "server/*.js"
  - "server/**/*.js"
exclude_paths:
- node_modules/
- .vscode
- server/spec/
- templates/