language: node_js
node_js:
    - "6.10.3"
branches:
  only:
    - master  
env:
  - NODE_ENV=test         
before_script:
  - npm install -g gulp-cli codeclimate-test-reporter
  - psql -c 'create database travisdb;' -U postgres
  - ./node_modules/.bin/sequelize db:migrate
cache:
  directories:
    - "node_modules"     
script: 
  - npm install
  - gulp   
after_success:       
  - codeclimate-test-reporter < ./coverage/lcov.info 
addons:
  postgresql: "9.6"
  code_climate:
    repo_token:
      secure: 562275715bc54638814f1c27bb4df1a9a2323f808c6eda859982040702c90942   
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=4QHTpRbU6DkqaTHX8qHZZYRQT2ftj9AAD